[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = [
    "export PYTHONUSERBASE=/app/.local",
    "pip install --user --upgrade pip",
    "pip install --user -r requirements.txt"
]

[phases.start]
cmds = [
    "export PYTHONUSERBASE=/app/.local",
    "export PATH=$PYTHONUSERBASE/bin:$PATH",
    "python3 -m gunicorn app:app"
]